### ISSUE TITLE
Possible BUG?

### ISSUE THREAD

**Issue by ALIVE321** [jasonppy/PromptingWhisper#1]
https://github.com/jasonppy/PromptingWhisper/blob/96fc999977a5f43152f1d49f088b18015deeba9d/data/visspeech.py#L140C1-L140C1

The `multilingual` flag in `get_tokenizer` is set as the opposite of `.en`, which is not reasonable.

**Comment by jasonppy** [comment]
tokenizer is never used in avsr.py or visspeech.py, so it will have no effects. However the logic is indeed wrong

Thanks for letting me know, I'll fix it

**Comment by yuhangear** [comment]
Hi,can you tell me What the beam size is set during decoding?

**Comment by ALIVE321** [comment]
> Hi,can you tell me What the beam size is set during decoding?

default as None to be greedy search.

**Comment by yuhangear** [comment]
Hi,
I attempted to use Hugging Face's code to decode with the Whisper-Large model for SEAME. In comparison to the decoding results for Whisper-Default mentioned in Table 4 of the paper, there seems to be a discrepancy between our results, possibly due to differences in language identification. Your results are devman: MER 51.55 and devsg: MER 61.36, while my results are devman: MER 38.2 and devsg: MER 65.0. Were these results also obtained using greedy search for decoding?

**Comment by ALIVE321** [comment]
> Hi, I attempted to use Hugging Face's code to decode with the Whisper-Large model for SEAME. In comparison to the decoding results for Whisper-Default mentioned in Table 4 of the paper, there seems to be a discrepancy between our results, possibly due to differences in language identification. Your results are devman: MER 51.55 and devsg: MER 61.36, while my results are devman: MER 38.2 and devsg: MER 65.0. Were these results also obtained using greedy search for decoding?

Hi, i'm not the author, and didn't reproduce CS-related exps. Maybe open another issue for their answer. ^^

**Comment by yuhangear** [comment]
Thank you for your reminder.

**Comment by jasonppy** [comment]
> Hi,can you tell me What the beam size is set during decoding?

beam size is set to 5 in all experiments. As can be seen from the scripts, e.g. https://github.com/jasonppy/PromptingWhisper/blob/main/scripts/seame.sh#L31

**Comment by jasonppy** [comment]
> Hi, I attempted to use Hugging Face's code to decode with the Whisper-Large model for SEAME. In comparison to the decoding results for Whisper-Default mentioned in Table 4 of the paper, there seems to be a discrepancy between our results, possibly due to differences in language identification. Your results are devman: MER 51.55 and devsg: MER 61.36, while my results are devman: MER 38.2 and devsg: MER 65.0. Were these results also obtained using greedy search for decoding?

Not sure if my previous reply also apply to this (I used beam size of 5). But feel free to open a new issue for discussing this
