### ISSUE TITLE
Can you provide me with the details of the decoding process?

### ISSUE THREAD

**Issue by yuhangear** [jasonppy/PromptingWhisper#2]
Hi, 

I attempted to use Hugging Face's code to decode with the Whisper-Large model for SEAME. In comparison to the decoding results for Whisper-Default mentioned in Table 4 of the paper,

there seems to be a discrepancy between our results, possibly due to differences in language identification. Your results are devman: MER 51.55 and devsg: MER 61.36, while my results are devman: MER 38.2 and devsg: MER 65.0. Were these results also obtained using greedy search for decoding?

**Comment by jasonppy** [comment]
Sorry for the late reply. The results are obtained by using beam search with beam size equals to 5
