### ISSUE TITLE
Is PromptingWhisper helpful if you want to transcribe a bilingual conversation between two speakers?

### ISSUE THREAD

**Issue by joiemoie** [jasonppy/PromptingWhisper#7]
I found this paper and it seems really interesting. I think it could address the use case of translating between multiple languages in the same audio.

**Comment by jasonppy** [comment]
Hi joiemoie,

Thanks for the kind words, yes I do think it could transcribe a bilingual conversation between two speakers. the CS-ASR paper already show the bilingual part, the multi-speaker part might be enabled by using prompt like speaker A: .... speaker B ...
